# Pandas - DataFrame and Series
- Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. 
- It provides two primary data structures: Series and DataFrame.
- A series is a one-dimensional array-like object, while DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axex (rows and columns)

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\rushi\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rushi\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rushi\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rushi\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rushi\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\rushi\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

### Series from list

In [3]:
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series: \n", series)

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
type(series)

pandas.core.series.Series

### Series from Dictionary

In [5]:
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print("Series using dict: \n", series_dict)

Series using dict:
 a    1
b    2
c    3
dtype: int64

In [6]:
data = [10, 20, 30]
Index = ['a', 'b', 'c']
pd.Series(data,index=Index)

a    10
b    20
c    30
dtype: int64

# DataFrame

#### Create a DataFrame from a dictionary of list.

In [7]:
data = {
    'Name':['krish', 'John', 'Jack'],
    'Age':[25, 30, 45],
    'City': ['Pune', 'Mumbai', 'Solapur']

}
indexes = [1,2,3]
df0 = pd.DataFrame(data, index=indexes)

In [8]:
print(type(df0))

<class 'pandas.core.frame.DataFrame'>

In [9]:
## Converting DataFrame into Numpy Array
import numpy as np
np.array(df0)

array([['krish', 25, 'Pune'],
       ['John', 30, 'Mumbai'],
       ['Jack', 45, 'Solapur']], dtype=object)

In [10]:
df_sample = [1,2,3,4,5]
pd.DataFrame(df_sample)

   0
0  1
1  2
2  3
3  4
4  5

In [11]:
s = np.array(df_sample)
s.dtype

dtype('int64')

In [12]:
## Create a Data Frame From a List of Dictionaries

data = [
    {'Name':'Krish', 'Age':25, 'City':'Pune'},
    {'Name':'John', 'Age':32, 'City':'Pune'},
    {'Name':'Bappy', 'Age':31, 'City':'Pune'},
    {'Name':'Jack', 'Age':27, 'City':'Pune'},
]
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age  City
0  Krish   25  Pune
1   John   32  Pune
2  Bappy   31  Pune
3   Jack   27  Pune
<class 'pandas.core.frame.DataFrame'>

In [13]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

In [14]:
#15:07
df = pd.read_csv("Sales_data.csv")
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [15]:
df.tail()

     Order ID  Amount  Profit  Quantity     Category Sub-Category PaymentMode
1495  B-25700       7      -3         2     Clothing  Hankerchief         COD
1496  B-25757    3151     -35         7     Clothing     Trousers         EMI
1497  B-25973    4141    1698        13  Electronics     Printers         COD
1498  B-25698       7      -2         1     Clothing  Hankerchief         COD
1499  B-25993    4363     305         5    Furniture       Tables         EMI

## loc and iloc
#### 1. Indexing Method
- loc:

    - Uses label-based indexing.
    - You can access rows and columns by their labels (i.e., the actual names of the index or column).
    - Syntax: df.loc[row_label, column_label]

- iloc:

    - Uses integer-based indexing.
    - You can access rows and columns by their integer position (i.e., the index number).
    - Syntax: df.iloc[row_index, column_index]

#### 2. Inclusivity
    - loc:

        - The end index is inclusive. For example, if you use df.loc[0:1], it will include both rows 0 and 1.
        
    - iloc:
        - The end index is exclusive. For example, if you use df.iloc[0:1], it will include only row 0.

#### 3. Use Cases
    - loc:
        - Useful when you want to access data based on the actual labels of the DataFrame.
        - Example: If you have a DataFrame with a custom index (like names or dates), you would use loc to access
        data by those labels.

    - iloc:
        - Useful when you want to access data based on the position of the rows and columns, regardless of their labels.
        - Example: If you want to access the first row or the first column without caring about what they are named, you would use iloc.

In [16]:
data = {
    'Name':['krish', 'John', 'Jack'],
    'Age':[25, 30, 45],
    'City': ['Pune', 'Mumbai', 'Solapur']
}
df_0 = pd.DataFrame(data)

In [17]:
type(df_0['Name'])

pandas.core.series.Series

In [18]:
type(df_0)

pandas.core.frame.DataFrame

In [19]:
df_0

    Name  Age     City
0  krish   25     Pune
1   John   30   Mumbai
2   Jack   45  Solapur

In [20]:
df_0.loc[0]

Name    krish
Age        25
City     Pune
Name: 0, dtype: object

In [21]:
df_0.iloc[0]

Name    krish
Age        25
City     Pune
Name: 0, dtype: object

In [22]:
df_0.iloc[0][0]

C:\Users\rushi\AppData\Local\Temp\ipykernel_18384\64217352.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_0.iloc[0][0]

'krish'

In [23]:
df_0.loc[0][0]

C:\Users\rushi\AppData\Local\Temp\ipykernel_18384\1987814575.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_0.loc[0][0]

'krish'

#### loc example - label-based indexing:

In [24]:
df_0

    Name  Age     City
0  krish   25     Pune
1   John   30   Mumbai
2   Jack   45  Solapur

In [25]:
df_0.loc[0:1, ["Name", "City"]]  # Access rows 0 to 1 and columns 'Name' and 'City'

    Name    City
0  krish    Pune
1   John  Mumbai

#### iloc Example -  position-based indexing:

In [26]:
df_0.iloc[0:2,[0,2]]  # Access rows 0 to 1 (exclusive of 2) and columns at index 0 and 2

    Name    City
0  krish    Pune
1   John  Mumbai

In [32]:
df_0

    Name  Age     City
0  krish   25     Pune
1   John   30   Mumbai
2   Jack   45  Solapur

## Accessing a specified element

##### Accessing a specified element using `at` - `row index` and `columns label`

In [34]:
data = {
    'Name':['krish', 'John', 'Jack'],
    'Age':[25, 30, 45],
    'City': ['Pune', 'Mumbai', 'Solapur']
}
df_0 = pd.DataFrame(data)

In [35]:
df_0.at[1, 'Age']

np.int64(30)

In [39]:
df_0.at[2, 'Name']

'Jack'

In [42]:
df_0

    Name  Age     City
0  krish   25     Pune
1   John   30   Mumbai
2   Jack   45  Solapur

##### Accessing a specified element using `iat` - i.e. `row index` and `column index`

In [41]:
df_0.iat[2,2]

'Solapur'

In [44]:
df_0.iat[2,1]

np.int64(45)

### Data Manipulation with DataFrame

In [56]:
df_0

    Name  Age     City
0  krish   25     Pune
1   John   30   Mumbai
2   Jack   45  Solapur

##### Adding a Column to DataFrame

In [65]:
df_0['Salary'] = [35000, 45000, 55000]
df_0

    Name  Age     City  Salary
0  krish   25     Pune   35000
1   John   30   Mumbai   45000
2   Jack   45  Solapur   55000

##### Removing Column From DataFrame

In [66]:
df_0.drop("Salary",axis=1)

    Name  Age     City
0  krish   25     Pune
1   John   30   Mumbai
2   Jack   45  Solapur

In [67]:
df_0

    Name  Age     City  Salary
0  krish   25     Pune   35000
1   John   30   Mumbai   45000
2   Jack   45  Solapur   55000

In [68]:
df_0.drop("Salary", axis=1, inplace=True)

In [69]:
df_0

    Name  Age     City
0  krish   25     Pune
1   John   30   Mumbai
2   Jack   45  Solapur

In [73]:
## Add Age with 1 year to the `Age` column
df_0['Age'] = df_0['Age']+1

In [74]:
df_0

    Name  Age     City
0  krish   26     Pune
1   John   31   Mumbai
2   Jack   46  Solapur

In [75]:
df_0.drop(0)

   Name  Age     City
1  John   31   Mumbai
2  Jack   46  Solapur

In [76]:
df_0

    Name  Age     City
0  krish   26     Pune
1   John   31   Mumbai
2   Jack   46  Solapur

In [77]:
df_0.drop(0, inplace=True)

In [78]:
df_0

   Name  Age     City
1  John   31   Mumbai
2  Jack   46  Solapur

In [79]:
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

#### Display  the data types of each column

In [80]:
df.dtypes

Order ID        object
Amount           int64
Profit           int64
Quantity         int64
Category        object
Sub-Category    object
PaymentMode     object
dtype: object

##### Statistical Summary / Describe the DataFrame

In [81]:
print("Statisticsl Summary: \n")
df.describe()

Statisticsl Summary:

            Amount      Profit     Quantity
count  1500.000000  1500.00000  1500.000000
mean    291.847333    24.64200     3.743333
std     461.924620   168.55881     2.184942
min       4.000000 -1981.00000     1.000000
25%      47.750000   -12.00000     2.000000
50%     122.000000     8.00000     3.000000
75%     326.250000    38.00000     5.000000
max    5729.000000  1864.00000    14.000000